import type { ScheduleCourse, ScheduleCourseInput } from "@/types/schedule";

export const emptyCourseInput: ScheduleCourseInput = {
  itemType: "course",
  courseName: "",
  teacher: "",
  weekday: 1,
  startTime: "08:00",
  endTime: "09:40",
  location: "",
  startWeek: 1,
  endWeek: 16,
  weekType: "all",
  visibility: "private",
  showOnProfile: false,
  participateInMatching: true,
  status: "must_go",
  reminderMinutes: 10,
  isHidden: false,
  note: "",
};

export const initialCourses: ScheduleCourse[] = [
  {
    id: "course-1",
    itemType: "course",
    courseName: "计量经济学",
    teacher: "陈老师",
    weekday: 2,
    startTime: "10:00",
    endTime: "11:40",
    location: "经管楼 B302",
    startWeek: 1,
    endWeek: 16,
    weekType: "all",
    visibility: "public",
    showOnProfile: true,
    participateInMatching: true,
    status: "looking_study_partner",
    reminderMinutes: 30,
    isHidden: false,
    note: "",
  },
  {
    id: "course-2",
    itemType: "course",
    courseName: "传播学专题",
    teacher: "李老师",
    weekday: 4,
    startTime: "14:00",
    endTime: "15:40",
    location: "三教 205",
    startWeek: 3,
    endWeek: 14,
    weekType: "all",
    visibility: "private",
    showOnProfile: false,
    participateInMatching: false,
    status: "sometimes",
    reminderMinutes: 10,
    isHidden: false,
    note: "",
  },
  {
    id: "course-3",
    itemType: "course",
    courseName: "学术写作",
    teacher: "王老师",
    weekday: 5,
    startTime: "16:00",
    endTime: "17:40",
    location: "文科楼 410",
    startWeek: 1,
    endWeek: 12,
    weekType: "odd",
    visibility: "public",
    showOnProfile: true,
    participateInMatching: true,
    status: "looking_classmate",
    reminderMinutes: 60,
    isHidden: false,
    note: "",
  },
  {
    id: "personal-1",
    itemType: "personal",
    courseName: "和室友出去吃饭",
    teacher: "",
    weekday: 5,
    startTime: "18:30",
    endTime: "20:00",
    location: "学校南门",
    startWeek: 1,
    endWeek: 16,
    weekType: "all",
    visibility: "private",
    showOnProfile: false,
    participateInMatching: false,
    status: "must_go",
    reminderMinutes: 30,
    isHidden: false,
    note: "已经约好，不要排别的事情",
  },
];
